export const NOTIFICATION_TYPES = Object.freeze({
  NEW_MESSAGE: "NEW_MESSAGE",

  CAR_RENT_ADDED: "CAR_RENT_ADDED",
  CAR_RENT_DELETED: "CAR_RENT_DELETED",
  CAR_BUY_ADDED: "CAR_BUY_ADDED",
  CAR_BUY_DELETED: "CAR_BUY_DELETED",

  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_ACCEPTED: "BOOKING_ACCEPTED",
  BOOKING_REJECTED: "BOOKING_REJECTED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",

  ORDER_CREATED: "ORDER_CREATED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_ACCEPTED: "ORDER_ACCEPTED",
  ORDER_REJECTED: "ORDER_REJECTED",
  ORDER_COMPLETED: "ORDER_COMPLETED",

  ORDER_BUY_CREATED: "ORDER_BUY_CREATED",
  ORDER_BUY_CANCELLED: "ORDER_BUY_CANCELLED",
  ORDER_BUY_ACCEPTED: "ORDER_BUY_ACCEPTED",
  ORDER_BUY_REJECTED: "ORDER_BUY_REJECTED",
  ORDER_BUY_COMPLETED: "ORDER_BUY_COMPLETED",

  OFFER_CREATED: "OFFER_CREATED",
  OFFER_ACCEPTED: "OFFER_ACCEPTED",
  OFFER_REJECTED: "OFFER_REJECTED",

  SYSTEM_NOTIFICATION: "SYSTEM_NOTIFICATION",
});

export const ENTITY_TYPES = Object.freeze({
  ORDER:       "Order",
  MESSAGE:     "Message",
  CAR:         "Car",
  USER:        "user",
  MARKETPLACE: "MarketplaceOrder",
});
