import type { MarketplaceCar } from "../types";

export const MOCK_RENT_CARS: MarketplaceCar[] = [
  {
    id: "rent-1",
    name: "Toyota Camry 2024",
    brand: "Toyota",
    model: "Camry",
    year: 2024,
    location: "Cairo",
    pricePerDay: 1200,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 5,
    mileage: 12000,
    rating: 4.9,
    reviewCount: 87,
    images: ["/assets/images/landing/car1.png"],
    available: true,
    isNew: true,
    badge: "مميز",
  },
  {
    id: "rent-2",
    name: "Kia Sportage 2024",
    brand: "Kia",
    model: "Sportage",
    year: 2024,
    location: "Cairo",
    pricePerDay: 1800,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "suv",
    seats: 5,
    mileage: 8500,
    rating: 4.7,
    reviewCount: 154,
    images: ["/assets/images/landing/car3.png"],
    available: true,
    isNew: true,
  },
  {
    id: "rent-3",
    name: "Mercedes C200 2023",
    brand: "Mercedes",
    model: "C200",
    year: 2023,
    location: "Alexandria",
    pricePerDay: 3500,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 4,
    mileage: 22000,
    rating: 5.0,
    reviewCount: 63,
    images: ["/assets/images/landing/car2.png"],
    available: true,
    isNew: false,
    badge: "حجز فوري",
  },
  {
    id: "rent-4",
    name: "Hyundai Elantra 2024",
    brand: "Hyundai",
    model: "Elantra",
    year: 2024,
    location: "Giza",
    pricePerDay: 950,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 5,
    mileage: 5000,
    rating: 4.8,
    reviewCount: 112,
    images: ["/assets/images/landing/car1.png"],
    available: true,
    isNew: true,
  },
  {
    id: "rent-5",
    name: "Toyota Corolla 2023",
    brand: "Toyota",
    model: "Corolla",
    year: 2023,
    location: "Cairo",
    pricePerDay: 1100,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "hybrid",
    bodyType: "sedan",
    seats: 5,
    mileage: 18000,
    rating: 4.6,
    reviewCount: 210,
    images: ["/assets/images/landing/car2.png"],
    available: true,
    isNew: false,
  },
  {
    id: "rent-6",
    name: "Chevrolet Malibu 2023",
    brand: "Chevrolet",
    model: "Malibu",
    year: 2023,
    location: "Sharm El-Sheikh",
    pricePerDay: 1350,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 5,
    mileage: 31000,
    rating: 4.5,
    reviewCount: 78,
    images: ["/assets/images/landing/car3.png"],
    available: true,
    isNew: false,
  },
  {
    id: "rent-7",
    name: "BMW 3 Series 2024",
    brand: "BMW",
    model: "3 Series",
    year: 2024,
    location: "Cairo",
    pricePerDay: 4200,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 5,
    mileage: 6000,
    rating: 4.9,
    reviewCount: 45,
    images: ["/assets/images/landing/car1.png"],
    available: true,
    isNew: true,
    badge: "مميز",
  },
  {
    id: "rent-8",
    name: "Nissan X-Trail 2023",
    brand: "Nissan",
    model: "X-Trail",
    year: 2023,
    location: "Alexandria",
    pricePerDay: 2100,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "suv",
    seats: 7,
    mileage: 24000,
    rating: 4.6,
    reviewCount: 93,
    images: ["/assets/images/landing/car2.png"],
    available: true,
    isNew: false,
  },
  {
    id: "rent-9",
    name: "Volkswagen Passat 2022",
    brand: "Volkswagen",
    model: "Passat",
    year: 2022,
    location: "Giza",
    pricePerDay: 1600,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 5,
    mileage: 38000,
    rating: 4.4,
    reviewCount: 67,
    images: ["/assets/images/landing/car3.png"],
    available: true,
    isNew: false,
  },
  {
    id: "rent-10",
    name: "Honda Accord 2024",
    brand: "Honda",
    model: "Accord",
    year: 2024,
    location: "Cairo",
    pricePerDay: 1900,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "hybrid",
    bodyType: "sedan",
    seats: 5,
    mileage: 3000,
    rating: 4.8,
    reviewCount: 41,
    images: ["/assets/images/landing/car1.png"],
    available: true,
    isNew: true,
  },
  {
    id: "rent-11",
    name: "Mitsubishi Eclipse Cross 2023",
    brand: "Mitsubishi",
    model: "Eclipse Cross",
    year: 2023,
    location: "Hurghada",
    pricePerDay: 1700,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "suv",
    seats: 5,
    mileage: 15000,
    rating: 4.5,
    reviewCount: 58,
    images: ["/assets/images/landing/car2.png"],
    available: true,
    isNew: false,
  },
  {
    id: "rent-12",
    name: "Kia K5 2024",
    brand: "Kia",
    model: "K5",
    year: 2024,
    location: "Cairo",
    pricePerDay: 1450,
    priceTotal: 0,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 5,
    mileage: 7000,
    rating: 4.7,
    reviewCount: 72,
    images: ["/assets/images/landing/car3.png"],
    available: true,
    isNew: true,
  },
];

export const MOCK_SALE_CARS: MarketplaceCar[] = [
  {
    id: "sale-1",
    name: "Hyundai Elantra 2023",
    brand: "Hyundai",
    model: "Elantra",
    year: 2023,
    location: "Cairo",
    pricePerDay: 0,
    priceTotal: 850000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 5,
    mileage: 25000,
    rating: 4.6,
    reviewCount: 67,
    images: ["/assets/images/landing/car1.png"],
    available: true,
    isNew: false,
  },
  {
    id: "sale-2",
    name: "Toyota Land Cruiser 2024",
    brand: "Toyota",
    model: "Land Cruiser",
    year: 2024,
    location: "Cairo",
    pricePerDay: 0,
    priceTotal: 4800000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "suv",
    seats: 7,
    mileage: 5000,
    rating: 4.9,
    reviewCount: 45,
    images: ["/assets/images/landing/car2.png"],
    available: true,
    isNew: true,
    badge: "مميز",
  },
  {
    id: "sale-3",
    name: "Kia Sportage 2023",
    brand: "Kia",
    model: "Sportage",
    year: 2023,
    location: "Alexandria",
    pricePerDay: 0,
    priceTotal: 1550000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "suv",
    seats: 5,
    mileage: 32000,
    rating: 4.7,
    reviewCount: 112,
    images: ["/assets/images/landing/car3.png"],
    available: true,
    isNew: false,
  },
  {
    id: "sale-4",
    name: "BMW X5 2022",
    brand: "BMW",
    model: "X5",
    year: 2022,
    location: "Cairo",
    pricePerDay: 0,
    priceTotal: 6200000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "suv",
    seats: 5,
    mileage: 42000,
    rating: 4.8,
    reviewCount: 38,
    images: ["/assets/images/landing/car1.png"],
    available: true,
    isNew: false,
    badge: "مميز",
  },
  {
    id: "sale-5",
    name: "Mercedes GLC 2023",
    brand: "Mercedes",
    model: "GLC",
    year: 2023,
    location: "Giza",
    pricePerDay: 0,
    priceTotal: 5100000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "suv",
    seats: 5,
    mileage: 18000,
    rating: 4.9,
    reviewCount: 29,
    images: ["/assets/images/landing/car2.png"],
    available: true,
    isNew: false,
  },
  {
    id: "sale-6",
    name: "Nissan Sunny 2022",
    brand: "Nissan",
    model: "Sunny",
    year: 2022,
    location: "Cairo",
    pricePerDay: 0,
    priceTotal: 480000,
    transmission: "manual",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 5,
    mileage: 55000,
    rating: 4.3,
    reviewCount: 143,
    images: ["/assets/images/landing/car3.png"],
    available: true,
    isNew: false,
  },
  {
    id: "sale-7",
    name: "Chevrolet Captiva 2023",
    brand: "Chevrolet",
    model: "Captiva",
    year: 2023,
    location: "Alexandria",
    pricePerDay: 0,
    priceTotal: 1150000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "suv",
    seats: 7,
    mileage: 21000,
    rating: 4.5,
    reviewCount: 84,
    images: ["/assets/images/landing/car1.png"],
    available: true,
    isNew: false,
  },
  {
    id: "sale-8",
    name: "Volkswagen Tiguan 2024",
    brand: "Volkswagen",
    model: "Tiguan",
    year: 2024,
    location: "Cairo",
    pricePerDay: 0,
    priceTotal: 2900000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "suv",
    seats: 5,
    mileage: 8000,
    rating: 4.7,
    reviewCount: 56,
    images: ["/assets/images/landing/car2.png"],
    available: true,
    isNew: true,
  },
  {
    id: "sale-9",
    name: "Honda Civic 2023",
    brand: "Honda",
    model: "Civic",
    year: 2023,
    location: "Giza",
    pricePerDay: 0,
    priceTotal: 1100000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 5,
    mileage: 28000,
    rating: 4.6,
    reviewCount: 91,
    images: ["/assets/images/landing/car3.png"],
    available: true,
    isNew: false,
  },
  {
    id: "sale-10",
    name: "Toyota Yaris 2022",
    brand: "Toyota",
    model: "Yaris",
    year: 2022,
    location: "Cairo",
    pricePerDay: 0,
    priceTotal: 580000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "hatchback",
    seats: 5,
    mileage: 48000,
    rating: 4.4,
    reviewCount: 167,
    images: ["/assets/images/landing/car1.png"],
    available: true,
    isNew: false,
  },
  {
    id: "sale-11",
    name: "Mitsubishi Outlander 2024",
    brand: "Mitsubishi",
    model: "Outlander",
    year: 2024,
    location: "Sharm El-Sheikh",
    pricePerDay: 0,
    priceTotal: 2200000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "suv",
    seats: 7,
    mileage: 4000,
    rating: 4.8,
    reviewCount: 33,
    images: ["/assets/images/landing/car2.png"],
    available: true,
    isNew: true,
  },
  {
    id: "sale-12",
    name: "Kia Cerato 2023",
    brand: "Kia",
    model: "Cerato",
    year: 2023,
    location: "Cairo",
    pricePerDay: 0,
    priceTotal: 720000,
    transmission: "automatic",
    fuelType: "petrol",
    bodyType: "sedan",
    seats: 5,
    mileage: 36000,
    rating: 4.5,
    reviewCount: 108,
    images: ["/assets/images/landing/car3.png"],
    available: true,
    isNew: false,
  },
];
